# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "new_agent_pool"

variables:
- name: CloudInitContent

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path .\AzureResourceGroup5\Cloud-Init.txt -Raw
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

- script: |
    echo $(CloudInitContent)

# Step to list files in AzureResourceGroup5 for debugging
- script: |
    echo "Listing files in AzureResourceGroup5:"
    ls $(Build.SourcesDirectory)/AzureResourceGroup5

# Step to print Build Sources Directory for verification
- script: |
    echo "Build Sources Directory: $(Build.SourcesDirectory)"

# Azure ARM template deployment
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f9e97e5c-73ff-4718-b630-1b42b0edea59)'
    subscriptionId: 'f9e97e5c-73ff-4718-b630-1b42b0edea59'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'HK'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\AzureResourceGroup5\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\AzureResourceGroup5\azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'
