# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "new_agent_pool"

variables:
- name: CloudInitContent

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path .\AzureResourceGroup2\cloud_init.txt -Raw
      Write-Host $CloudContent$endedContent = [Convert]::ToBase64Streing([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $endedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$endedContent"

- script: |
    echo $(CloudInitContent)


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f9e97e5c-73ff-4718-b630-1b42b0edea59)'
    subscriptionId: 'f9e97e5c-73ff-4718-b630-1b42b0edea59'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'HK'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '''$(Build.SourcesDirectory)\AzureResourceGroup2\azuredeploy.json'''
    csmParametersFile: '$(Build.SourcesDirectory)\AzureResourceGroup2\azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'