trigger:
- master


pool: "new_agent_pool"

variables:
- name: CloudInitContent

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path "$(Build.SourcesDirectory)/AzureResourceGroup5/cloud-init.txt" | Out-String
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

- script: |
    echo $(CloudInitContent)

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'evd_subscription'
    subscriptionId: '82477da1-4158-40e9-a78b-14959ac4bd55'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'evd_resource_group'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/AzureResourceGroup5/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/AzureResourceGroup5/azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)' 
    deploymentMode: 'Validation'
