trigger:
  - master

pool: "new_agent_pool"

variables:
  - name: CloudInitContent

steps:
# Step to read and encode Cloud-Init file to Base64
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path "$(Build.SourcesDirectory)/AzureResourceGroup5/Cloud-Init.txt" -Raw
      Write-Host "Cloud-Init content before encoding:"
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host "Base64 Encoded Cloud-Init content:"
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

# Display CloudInit content (for debugging purposes)
- script: |
    echo "Encoded CloudInitContent variable for debugging:"
    echo $(CloudInitContent)

# Step to list files in AzureResourceGroup5 for debugging
- script: |
    echo "Listing files in AzureResourceGroup5:"
    dir $(Build.SourcesDirectory)\AzureResourceGroup5

# Step to print Build Sources Directory for verification
- script: |
    echo "Build Sources Directory: $(Build.SourcesDirectory)"

# Publish CloudInitContent as a pipeline artifact for use in the Deployment Pipeline
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'CloudInitArtifact'
