trigger:
  - master

pool: "new_agent_pool"

variables:
  - name: CloudInitContent

steps:
# Step to encode and save CloudInitContent to a file
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path "$(Build.SourcesDirectory)/AzureResourceGroup5/Cloud-Init.txt" -Raw
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Set-Content -Path "$(Pipeline.Workspace)/CloudInitContent.txt" -Value $encodedContent
      Write-Host "CloudInitContent has been encoded and saved to CloudInitContent.txt"

# Display CloudInitContent (for debugging purposes)
- script: |
    echo "Encoded CloudInitContent saved to CloudInitContent.txt file."

# Step to list files in AzureResourceGroup5 for debugging
- script: |
    echo "Listing files in AzureResourceGroup5:"
    dir $(Build.SourcesDirectory)\AzureResourceGroup5

# Step to print Build Sources Directory for verification
- script: |
    echo "Build Sources Directory: $(Build.SourcesDirectory)"

# Publish CloudInitContent as a pipeline artifact for use in the Deployment Pipeline
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/CloudInitContent.txt'
    artifact: 'CloudInitArtifact'
